# Generated by Django 3.2 on 2021-05-04 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_txt',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
