# Generated by Django 3.2 on 2021-05-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_exam', '0002_exam_txt_date_ajout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_txt',
            old_name='title',
            new_name='name',
        ),
    ]
