# Generated by Django 3.2 on 2021-05-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_exam', '0003_rename_title_exam_txt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_txt',
            name='file',
            field=models.FileField(upload_to='exam'),
        ),
    ]
