# Generated by Django 3.2 on 2021-05-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_exam', '0004_alter_exam_txt_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_txt',
            old_name='file',
            new_name='exam_file',
        ),
    ]
